# k8s/frontend/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tourism-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tourism-frontend
  template:
    metadata:
      labels:
        app: tourism-frontend
    spec:
      containers:
        - name: node-app
          image: weirung/tourism_keelung_frontend:latest  # 你 build 推上去的映像
          ports:
            - containerPort: 3000
