# k8s/frontend/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: tourism-frontend
spec:
  type: ClusterIP
  selector:
    app: tourism-frontend
  ports:
    - port: 80
      targetPort: 3000
